name: TestScripts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: pCYSl5EDgo/cat@master
        id: read_recent
        with:
          path: issues.txt
      - run: |
          echo "ISSUE_NUMBER=${{ steps.read_recent.outputs.text }}" >> $GITHUB_ENV
          echo "ISSUE_MINUS_ONE=$((${{ steps.read_recent.outputs.text }}-1))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_FIVE=$((${{ steps.read_recent.outputs.text }}-5))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_SIX=$((${{ steps.read_recent.outputs.text }}-6))" >> $GITHUB_ENV
        shell: bash

      - name: Download Issues With end limit
        id: normalIssuesWithEndLimitWindows
        shell: pwsh
        run: ./hackspace-downloader.ps1 -l 2
      - name: Download Issues with start and end limit
        id: normalIssuesWithStartAndEndRangeWindows
        shell: pwsh
        run: ./hackspace-downloader.ps1 -f ${{ env.ISSUE_MINUS_SIX }} -l ${{ env.ISSUE_MINUS_FIVE }}
      - name: Download Issues with start limit
        id: normalIssuesWithRangeAndStartLimitWindows
        shell: pwsh
        run: ./hackspace-downloader.ps1 -f ${{ env.ISSUE_MINUS_ONE }}
      - name: "Check file existence Windows"
        id: check_files
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: "issues/HS_01.pdf, issues/HS_02.pdf, issues/HS_${{ env.ISSUE_MINUS_SIX }}.pdf, issues/HS_${{ env.ISSUE_MINUS_FIVE }}.pdf,issues/HS_${{ env.ISSUE_MINUS_ONE }}.pdf,issues/HS_${{ env.ISSUE_NUMBER }}.pdf"
          fail: false
          ignore_case: true
      - name: lslah2
        run: Get-ChildItem issues/
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1

  bash-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: pCYSl5EDgo/cat@master
        id: read_recent
        with:
          path: issues.txt
      - run: |
          echo "ISSUE_NUMBER=${{ steps.read_recent.outputs.text }}" >> $GITHUB_ENV
          echo "ISSUE_MINUS_ONE=$((${{ steps.read_recent.outputs.text }}-1))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_FIVE=$((${{ steps.read_recent.outputs.text }}-5))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_SIX=$((${{ steps.read_recent.outputs.text }}-6))" >> $GITHUB_ENV
        
      - name: Download Issues with start limit Linux
        id: normalIssuesWithStartLimitLinux
        run: ./hackspace-downloader.sh -f ${{ env.ISSUE_MINUS_ONE }}
      - name: Download Issues with end limit Linux
        id: normalIssuesWithEndLimitLInux
        run: ./hackspace-downloader.sh -l 2
      - name: Download Issues with start and end limit Linux
        id: normalIssuesWithStartAndEndLimitLinux
        run: ./hackspace-downloader.sh -f ${{ env.ISSUE_MINUS_SIX }} -l ${{ env.ISSUE_MINUS_FIVE }}
      - name: download all books
        id: downloadallbooks
        run: ./hackspace-books-downloader.sh
      - name: "Check file existence linux"
        id: check_files
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: "issues/HS_1.pdf, issues/HS_2.pdf, issues/HS_${{ env.ISSUE_MINUS_SIX }}.pdf, issues/HS_${{ env.ISSUE_MINUS_FIVE }}.pdf,issues/HS_${{ env.ISSUE_MINUS_ONE }}.pdf,issues/HS_${{ env.ISSUE_NUMBER }}.pdf, special-issues/Book_of_Making_v1.pdf, special-issues/Book_of_Making-vol2.pdf"
          fail: false
          ignore_case: true
      - name: lslah
        run: ls -lah . issues/
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
  bash-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: pCYSl5EDgo/cat@master
        id: read_recent
        with:
          path: issues.txt
      - run: |
          echo "ISSUE_NUMBER=${{ steps.read_recent.outputs.text }}" >> $GITHUB_ENV
          echo "ISSUE_MINUS_ONE=$((${{ steps.read_recent.outputs.text }}-1))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_FIVE=$((${{ steps.read_recent.outputs.text }}-5))" >> $GITHUB_ENV
          echo "ISSUE_MINUS_SIX=$((${{ steps.read_recent.outputs.text }}-6))" >> $GITHUB_ENV
        
      - name: Download Issues with start limit Mac
        id: normalIssuesWithStartLimitMac
        run: ./hackspace-downloader.sh -f ${{ env.ISSUE_MINUS_ONE }}
      - name: Download Issues with start and end limit Mac
        id: normalIssuesWithEndLimitMac
        run: ./hackspace-downloader.sh -l 2
      - name: Download Issues with start and end limit Mac
        id: normalIssuesWithStartAndEndLimitMac
        run: ./hackspace-downloader.sh -f ${{ env.ISSUE_MINUS_SIX }} -l ${{ env.ISSUE_MINUS_FIVE }}
      - name: download all books
        id: downloadallbooks
        run: ./hackspace-books-downloader.sh
      - name: "Check file existence linux"
        id: check_files
        uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3.0.0
        with:
          files: "issues/HS_1.pdf, issues/HS_2.pdf, issues/HS_${{ env.ISSUE_MINUS_SIX }}.pdf, issues/HS_${{ env.ISSUE_MINUS_FIVE }}.pdf,issues/HS_${{ env.ISSUE_MINUS_ONE }}.pdf,issues/HS_${{ env.ISSUE_NUMBER }}.pdf, special-issues/Book_of_Making_v1.pdf, special-issues/Book_of_Making-vol2.pdf"
          fail: false
          ignore_case: true
      - name: lslah
        run: ls -lah . issues/
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
