name: Update latest issues

on:
  schedule:
    - cron: '0 12 * * *'  # every day at noon
  workflow_dispatch: {}

jobs:
  update-latest-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: update issues
        id: updateIssues
        run: bash ./script-for-using-latest-version.sh
      - uses: pCYSl5EDgo/cat@master
        id: read_recent
        with:
          path: ./issues.txt
      - run: |
          echo "ISSUE_NUMBER=${{ steps.read_recent.outputs.text }}" >> $GITHUB_ENV
      - name: config git
        run: |
          git config --local user.email "1439809+joergi@users.noreply.github.com"
          git config --local user.name "Joergi via GitHub Actions"
      - name: Create Pull Request
        id: createAutoPR
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          title: new Issue ${{ env.ISSUE_NUMBER }} - Automated PR
          commit-message: new Issue ${{ env.ISSUE_NUMBER }} - Automated PR
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          body: Automated pull request for issue ${{ env.ISSUE_NUMBER }} created by GitHub Actions
          branch: automated_PR_for_update_issues
          branch-suffix: timestamp
          base: main
          delete-branch: true
          labels: "automerge"
      - name: Auto approve
        id: autoApprove
        if: steps.createAutoPR.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@6b8b2f82d50cea1e4329bcdfe940a6ceccbe528e # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.createAutoPR.outputs.pull-request-number }}
      - name: Enable Pull Request Automerge
        if: steps.createAutoPR.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          pull-request-number: ${{ steps.createAutoPR.outputs.pull-request-number }}
